services:

  web:
    image: convocacoes-web:1.0.0
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - ./.m2/:/root/.m2/repository/
