services:

  java:
    image: java:1.0.0
    container_name: java
    build:
      context: .
      dockerfile: ./docker/java/Dockerfile
    volumes:
      - .:/app
      - ./target-container/:/app/target/
      - ./.m2-container/:/root/.m2/repository/

  web:
    image: web:1.0.0
    container_name: web
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - ./target-container/:/app/target/
      - ./.m2-container/:/root/.m2/repository/
    depends_on:
      - java
