services:

  java:
    image: java:1.0.0
    build:
      context: .
      dockerfile: ./docker/java/Dockerfile

  web:
    image: web:1.0.0
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - ./.m2/:/root/.m2/repository/
    depends_on:
      - java
