@baseUrl = http://localhost:8080


# @name list_unidades
GET {{baseUrl}}/unidades

###

# @name create_unidade
POST {{baseUrl}}/unidades
Content-Type: application/json

{
    "nome": "Centro"
}

###

# @name get_unidade
GET {{baseUrl}}/unidades/4d8c7d70-96e5-44e7-8ca2-b2b4d3a94264

