@baseUrl = http://localhost:8080


# @name list_unidades
GET {{baseUrl}}/unidades

###

# @name create_unidade
POST {{baseUrl}}/unidades
Content-Type: application/json

{
    "nome": "Aleixo"
}

###

# @name update_unidade
PATCH {{baseUrl}}/unidades/049df595-3ab8-4ee4-a1af-cda6f05b6ccb
Content-Type: application/json

{
    "nome": "aleixo",
    "descricao": "Ao lado da Pemaza"
}

###

# @name get_unidade
GET {{baseUrl}}/unidades/049df595-3ab8-4ee4-a1af-cda6f05b6cc

###

# @name delete_unidade
DELETE {{baseUrl}}/unidades/049df595-3ab8-4ee4-a1af-cda6f05b6cc
